---
# tasks file for install_SUSE_HA_packages

- name: "Install packages needed for SUSE HA"
  package:
   name:  "{{ suse_ha_packages }}"
   state: "present"
  notify:
    - "Reboot"
    - "Wait for the machine(s) to be ready again"
